// BattleWack.h : main header file for the BATTLEWACK application
//

#if !defined(AFX_BATTLEWACK_H__8C71D187_0CC7_449D_884B_FE6A2081DC87__INCLUDED_)
#define AFX_BATTLEWACK_H__8C71D187_0CC7_449D_884B_FE6A2081DC87__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"       // main symbols
#include "Ship.h"
#include <afxsock.h>
#include <assert.h>
#include "mmsystem.h"
#include "HighScore.h"


/////////////////////////////////////////////////////////////////////////////
// CBattleWackApp:  This is the Actual Application
//					All of the code below is Generated by the AppWizard

class CBattleWackApp : public CWinApp
{
public:
	CBattleWackApp();

// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CBattleWackApp)
	public:
	virtual BOOL InitInstance();
	//}}AFX_VIRTUAL

// Implementation

public:
	virtual BOOL PreTranslateMessage(MSG* pMsg);
	//{{AFX_MSG(CBattleWackApp)
	afx_msg void OnAppAbout();
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};


/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_BATTLEWACK_H__8C71D187_0CC7_449D_884B_FE6A2081DC87__INCLUDED_)
